hosts = { 
  "workerNode" => { 
    :box => "ubuntu/jammy64",
    :hostname => "wr1",
    :ip => "192.168.41.100",
    :ram => "4096",
    :cpu => "2",
    :script => "../scripts/workerNodeInstall.sh"
  },

  "controlPlane" => { 
    :box => "ubuntu/jammy64",
    :hostname => "cr1",
    :ip => "192.168.41.101",
    :ram => "4096",
    :cpu => "2",
    :script => "../scripts/masterNodeInstall.sh"
  },
  
  "DNS" => {
    :box => "ubuntu/jammy64", 
    :hostname => "dns",
    :ip => "192.168.41.102",
    :ram => "2048",
    :cpu => "1",
    :script => "../scripts/bind9.sh"
  }

}

Vagrant.configure("2") do |config|
  
  hosts.each do |name, settings|
    config.vm.define name do |node|
      node.vm.box = settings[:box]
      node.vm.hostname = settings[:hostname]
      node.vm.network "private_network", ip: settings[:ip]

      node.vm.provider "libvirt" do |qe|
        qe.memory = settings[:ram]
        qe.cpus = settings[:cpu]
      end

      if settings[:script]
        node.vm.provision "shell", path: settings[:script]
      end

    end
  end
end


